# Generated by Django 3.2.8 on 2021-10-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portifolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolio',
            name='link',
            field=models.URLField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
