# Generated by Django 3.2.8 on 2021-11-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portifolio_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portifolio',
            new_name='Portifolio_cliente',
        ),
    ]
