# Generated by Django 3.2.8 on 2021-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('ID_Depoimentos', models.AutoField(primary_key=True, serialize=False)),
                ('imageDep', models.ImageField(upload_to='img_Depoimentos/%y')),
                ('nome_depoente', models.CharField(max_length=100)),
                ('depoimento', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='social_media',
            name='logomarca',
            field=models.ImageField(upload_to='Social_Media/%y'),
        ),
    ]
