# Generated by Django 3.2.8 on 2021-11-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211127_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depoimentos',
            new_name='Depoimento',
        ),
        migrations.RenameField(
            model_name='depoimento',
            old_name='depoimento',
            new_name='cliente_Dep',
        ),
    ]
